analyzer:
  enable-experiment:
    - nonfunction-type-aliases
    - variance
  exclude:
    - lib/**.g.dart
    - lib/**.gr.dart
    - lib/**.config.dart
    - build/**
    - lib/**.freezed.dart
    - '**/*.g.dart'
    - '**/graphql/**'
  language:
    strict-inference: true
    strict-raw-types: true
  plugins:
    - dart_code_metrics
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  errors:
    always_declare_return_types: error
    always_put_control_body_on_new_line: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    always_specify_types: error
    annotate_overrides: error
    avoid_catches_without_on_clauses: warning
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: info
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_escaping_inner_quotes: warning
    avoid_field_initializers_in_const_classes: error
    avoid_implementing_value_types: error
    avoid_init_to_null: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: error
    avoid_redundant_argument_values: info
    avoid_renaming_method_parameters: warning
    avoid_return_types_on_setters: info
    avoid_returning_null: warning
    avoid_returning_null_for_void: warning
    avoid_returning_this: info
    avoid_setters_without_getters: warning
    avoid_shadowing_type_parameters: error
    avoid_single_cascade_in_expression_statements: warning
    avoid_types_on_closure_parameters: ignore
    avoid_unnecessary_containers: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: warning
    camel_case_extensions: warning
    camel_case_types: error
    cascade_invocations: info
    cast_nullable_to_non_nullable: warning
    constant_identifier_names: warning
    curly_braces_in_flow_control_structures: warning
    diagnostic_describe_all_properties: warning
    directives_ordering: info
    empty_catches: warning
    empty_constructor_bodies: warning
    exhaustive_cases: error
    file_names: error
    flutter_style_todos: ignore
    implementation_imports: error
    join_return_with_assignment: warning
    library_names: error
    library_prefixes: error
    lines_longer_than_80_chars: warning
    missing_whitespace_between_adjacent_strings: warning
    no_runtimeType_toString: warning
    non_constant_identifier_names: error
    null_check_on_nullable_type_parameter: error
    null_closures: warning
    omit_local_variable_types: ignore
    one_member_abstracts: warning
    only_throw_errors: error
    overridden_fields: warning
    package_api_docs: warning
    parameter_assignments: error
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_asserts_with_message: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_contains: warning
    prefer_expression_function_bodies: ignore
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_typing_uninitialized_variables: warning
    provide_deprecation_message: error
    public_member_api_docs: ignore
    recursive_getters: error
    sized_box_for_whitespace: error
    sort_constructors_first: ignore
    type_annotate_public_apis: error
    use_full_hex_values_for_flutter_colors: warning
    use_key_in_widget_constructors: ignore
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 75
  metrics-exclude:
    - test/**
  rules:
    - avoid-returning-widgets:
        ignored-names:
          - makeTestableWidget
    - binary-expression-operand-order
    - no-equal-then-else
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-late-keyword
    - avoid-non-null-assertion
    - prefer-trailing-comma
    #    - avoid-unused-parameters
    - double-literal-format
    - no-equal-arguments
    - no-magic-number
    - no-object-declaration
    - prefer-intl-name
    - provide-correct-intl-args
    - no-magic-number
    - avoid-returning-widgets

    - member-ordering-extended:
        alphabetize: false
        order:
          - public-static-const-fields
          - private-static-const-fields
          - public-static-final-fields
          - private-static-final-fields
          - public-static-fields
          - private-static-fields
          - public-final-fields
          - private-final-fields
          - public-fields
          - public-getters-setters
          - private-fields
          - private-getters-setters
          - constructors
          - named-constructors
          - factory-constructors
          - overridden-methods
          - public-static-methods
          - public-methods
          - protected-methods
          - private-static-methods
          - private-methods
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_specify_types
    - always_use_package_imports
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - diagnostic_describe_all_properties
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - null_closures
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    #    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_generic_function_type_aliases
    #    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    #    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks
